name: Refresh profile SVGs

on:
  schedule:
  - cron: "*/13,*/37 * * * *"
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
    # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
    - name: generate github-contribution-grid-snake.svg
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          snake/github-contribution-grid-snake.svg
          snake/github-contribution-grid-snake-dark.svg?palette=github-dark
    # push the content of <build_dir> to a branch
    # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page

    - name: push github-contribution-grid-snake.svg to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: snake
        build_dir: snake
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-3d-contrib:
      runs-on: ubuntu-slim
      timeout-minutes: 1
      name: Generate GitHub profile 3D contrib
      steps:
        - uses: actions/checkout@v5
        - uses: yoshi389111/github-profile-3d-contrib@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
        - name: Commit & Push
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A .
            if git commit -m "generated 3D profile contrib"; then
                git push
            fi
