name: GitHub-Profile-3D-Contrib

on:
  schedule:
  - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub profile 3D contrib
    steps:
    - name: Generate trophy
      uses: Erik-Donath/github-profile-trophy@feature/generate-svg
      with:
        username: ${{ github.repository_owner }}
        output_path: trophy/trophy.svg
        token: ${{ secrets.GITHUB_TOKEN }}
